# Generated by Django 4.1.3 on 2024-06-17 08:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('informationapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arduino',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('temperature_info', models.IntegerField(default=0)),
                ('update_data', models.DateTimeField(default=django.utils.timezone.now)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informationapp.station')),
            ],
            options={
                'verbose_name': 'Arduino',
            },
        ),
    ]
